email_confirmation_tokens tablosunun eksikleri kapatıldı
mavidurak/mentor-api pull request #16
Opened 2020-10-11 00:11 UTC by saracalihan

2020-10-12 18:31 UTC, saracalihan commented
@ozziest  @teathedev  Lütfen **merge etmeyin** değişiklik yapıyorum

2020-10-26 17:31 UTC, teathedev requested changes

2020-10-26 17:31 UTC, teathedev commented on src/models/user.js
>      var charactersLength = characters.length;
Burayı da token üretirken gibi yapalım.

2020-10-26 19:00 UTC, saracalihan commented on src/models/user.js
>      var charactersLength = characters.length;
token, `this.username + this.email + Math.floor(Math.random() * 9999)` stringinin her karakterden sonra rastgele rakam eklenerek `encrypt()` fonksiyonu ile şifrelendi.

2020-11-02 18:06 UTC, teathedev commented on src/routes/authentications/index.js
> +  if (process.env.NODE_ENV === "development" || undefined) {
!process.env.NODE_ENV ||  process.env.NODE_ENV === "development"

2020-11-02 18:09 UTC, teathedev commented
e-posta'nın doğrulanıp doğrulanmadığını belirleyen bir boolean alan koyup, doğrulandığında token_value'yu silmek yerine o alanı true yaparsan daha iyi olur.

2020-11-16 17:52 UTC, teathedev commented on src/models/emailConfirmationTokens.js
> +    models.email_confirmation_token.prototype.createEmailConfirmationToken = async function () {
Bu fonksiyonu user model'inin içerisinde yapman daha doğru olur. Buradaki this yeni oluşacak bir obje olduğu için bir değeri yok, dolayısıyla user_id yi bulamaz. Ayrıca save fonksiyonu da olmadığı için database'de herhangi bir veri oluşmaz.

User model'i içerisinde this zaten user olacağı için bütün verilere sahip olacaksın. Daha sonra oluşturduğun token'ı emailConfirmationToken tablosuna yazabilirsin

2020-11-16 17:53 UTC, teathedev commented on src/models/user.js
> +    type: DataTypes.STRING,
BOOLEAN olması gerekiyor

2020-11-16 17:53 UTC, teathedev commented on src/models/user.js
> +    delete values.email_confirmation_token;
is_email_confirmed key'ini silmen gerekiyor.

2020-11-16 17:56 UTC, teathedev commented
E-posta adresinin doğrulanıp doğrulanmadığını authentication middleware'inde de kontrol etmemiz daha iyi olur. Oturum açtıktan sonra e-posta değiştirildiğinde doğrulanmadan işlem yapılmasını engeller.
NOT: white list'teki endpoint'lere hala istek atabilir.

2020-11-30 18:22 UTC, merged