Added token status feature for emailconfirmationtokens
mavidurak/mentor-api pull request #38
Opened 2021-01-16 17:18 UTC by halilseker

Issiue #35 solved

2021-01-19 18:27 UTC, teathedev requested changes

2021-01-19 18:27 UTC, teathedev commented on src/models/emailConfirmationTokens.js
> +    this.token_status='CONFIRMED';
= işaretinden önce ve sonra boşluk olması gerekiyor. Bu kod genelinde var. Yaptığın değişikliklere PR üzerinden bakarak düzeltebilirsin hepsini

2021-01-19 18:27 UTC, teathedev commented on src/models/emailConfirmationTokens.js
> +    token_status: {
Bu alanın adını 'status' olarak değiştirebilirsin. Zaten tablonun adında "token" var

2021-01-19 18:27 UTC, teathedev commented on src/models/emailConfirmationTokens.js
> +    this.token_status='CONFIRMED';
ayrıca burada kullanılan status'leri "PENDING", "CANCELED" ve "CONFIRMED" alanlarını bir dosya içerisinde enum olarak yapabilirsin. Bu tanımlamayı "src/constants" klasörü içerisinde bir dosya oluşturarak tutabilirsin. Dosyada "{}" olarak tutmalısın. Örnek olarak;
```
{
    PENDING: 'PENDING'
}
```

2021-01-19 18:27 UTC, teathedev commented on src/models/user.js
> +      status='CANCELLED';
Bu kontrol de SQL sorgusunda olması gerekiyor. Ayrıca status değiştirildikten sonra save işlemi yapılması gerekiyor.

2021-02-04 17:59 UTC, teathedev commented on src/models/emailConfirmationTokens.js
> +    await email_confirmation_token.save();
this.save olmasi lazim

2021-02-04 18:00 UTC, teathedev commented on src/routes/authentications/index.js
> +<<<<<<< HEAD
conflict

2021-02-04 18:01 UTC, teathedev commented on src/routes/authentications/index.js
> +<<<<<<< HEAD
diger dosyalarda da var. buradaki yaziyi aratirsan proje icerisinde bulabilirsin

2021-02-08 17:35 UTC, teathedev commented on src/models/user.js
> +      await email_confirmation_token.save();
değişken ismi yanlış. user_email_confirmation_token olması gerekiyor.

2021-02-08 17:37 UTC, teathedev commented on src/routes/healt.js
> +const express = require('express');
Bu işin ayrı bir pr'da yapılması gerekiyordu. Buradan silip ayrı bir pr olarak açar mısın?

Ayrıca url ve response issue'daki ile farklı

2021-02-15 13:56 UTC, halilseker commented
@halilseker
Degisken adi duzeltildi, healtcheck fonksiyonu bu issuedan ciakrildi

2021-03-03 01:06 UTC, saracalihan commented
@halilseker  issue @saracalihan 'a verildi, emeğin için teşekkürler.

2021-03-03 01:06 UTC, closed without merging